config/routes.rb
Future::Application.routes.draw do
  Mercury::Engine.routes

  get "message/index"

  resources :galleries

  resources :videos, :path =>  "/partners"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :contacts do 
    member { post :show }
  end

  resources :projects

  resources :goals, :path => "/center"

  resources :posts, :path => "/news" do
    member { post :show }
  end
  

  match "/posts/:id" => 'posts#show' 
  match "/posts" => 'posts#index' 
  match "/blog" => 'posts#index'

  match "/videos" => 'videos#index'

  get "home/index"

  root :to => "home#index"

  match "/sitemap.:format",
     :controller => "home",
     :action => "sitemap",
     :conditions => { :method => :get }

 
 mount Ckeditor::Engine => "/ckeditor"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :phone_number, :description, :job_title, :image, :website, :position
  mount_uploader :image, PostImageUploader
  validates :name, :presence => true
  validates :email, :presence => true
  validates :position, :presence => true
  validates :position, :inclusion => 1..100

  def to_param
  	"#{id} #{name}".parameterize
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	attr_accessible :description, :image, :video, :url_for_video
	mount_uploader :image, PostImageUploader
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :title, :content, :maps
end

app/models/message.rb
class Message < ActiveRecord::Base
 validates :content, :message_type, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :image, :title, :name, :content, :remote_image_url, :published_at, :sub_title, :publish
  mount_uploader :image, PostImageUploader
  validates :name, :title, :published_at, :content, :presence => true

  scope :all
  scope :published_posts, where(:publish => true)
  scope :unpublished_posts, where(:publish => false)


  def to_param
  	"#{id} #{sub_title}".parameterize
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :content
  validates :title, :presence => true, :length => { :minimum => 3 }
  validates :content, :presence => true
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :description, :logo, :homepage, :homepage_slogan, :position
  validates :homepage, :presence => true
  validates :homepage_slogan, :presence => true
  validates :position, :presence => true
  validates :position, :inclusion => 1..100
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
    @partners = Video.order("position asc")
    @messages = Message.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = Goal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@partners = Video.order("position asc")
    messages = Message.order("created_at desc")
    @homepage_message = nil
    messages.each do |message|
    	@homepage_message = message if message.message_type == "Homepage Message"
    end
  end

  def sitemap
  	@posts = Post.all
  	@contacts = Contact.all
  	@galleries = Gallery.all
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # GET /posts
  # GET /posts.json
  def index
    #nil if not logged in as admin
    @is_admin = current_admin_user
    if @is_admin != nil
      @posts = Post.order("created_at desc").page(params[:page]).per(10)
    else
      @posts = Post.published_posts.order("created_at desc").page(params[:page]).per(10)
    end

    @messages = Message.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.rss { render :layout => false }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    @is_admin = current_admin_user

    if params[:content] != nil && @is_admin != nil
      mercury_post = @post
      mercury_post.title = params[:content][:post_title][:value]
      mercury_post.content = params[:content][:post_content][:value]
      mercury_post.sub_title = params[:content][:post_sub_title][:value] if params[:content][:post_sub_title] != nil
      
      if params[:content][:post_publish][:value] != nil
        publish = params[:content][:post_publish][:value].chomp
        if publish.downcase == "true" 
          mercury_post.publish = true
        else
          mercury_post.publish = false
        end
      end 
      mercury_post.save!
      render text: ""
      else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @post }
      end
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base
  def index
    @videos = Video.order("created_at desc").page(params[:page]).per(10)
    @messages = Message.order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


	def is_current_page(path)
	  "active" if current_page?(path)
	end

 # def markdown(text)
    #Markdown.new(text, :hard_wrap, :autolink).to_html.html_safe
  #  rndr = Redcarpet::Render::HTML.new(:autolink => true, :hard_wrap => true)
  #  Redcarpet::Markdown.new(text, rndr);
#  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/_about_us.html.erb
<ul style="margin-bottom:20px;">
  <% @messages.each do |message| %>
  	<% if message.message_type == "About us" %>
	    <li>
	      <h1 class="main-heading"><%= message.title.html_safe if message.title? %></h1>
	      <div class="donate-info">
	        <hr>
	         <p class="donate"><%= message.content.html_safe if message.content? %></p>
	      </div>
	    </li>
  	<% end %> 
  <% end %> 
</ul>  

	

app/views/home/_announcement.html.erb
  <% @messages.each do |message| %>
  	<% if message.message_type == "Announcement" %>
        <div class="alert alert-block">
				  <button type="button" class="close" data-dismiss="alert">×</button>
				  <strong><%= message.title.html_safe if message.title? %></strong> <%= message.content.html_safe if message.content? %>
				</div> 
	    </li>
  	<% end %> 
  <% end %> 
	

app/views/home/_circle_links.html.erb
<section class="main">
	<ul class="ch-grid">
		<li>
			<a href="/projects" style="text-decoration:none;">
				<div class="ch-item ch-img-1">
					<div class="ch-info">
						<h3 style="margin-bottom:-80px;">The Project</h3>
						<p style="font-size:18px;">Aid through art <a href="/projects"></a></p>
					</div>
				</div>
				<span style="font-weight:bold;">THE PROJECT</span>
			</a>
		</li>
		<li>
			<a href="/center" style="text-decoration:none;">
				<div class="ch-item ch-img-2">
					<div class="ch-info">
						<h3 style="margin-bottom:-80px;">The Center</h3>
						<p style="font-size:18px;">Sierre Leone <a href="/center"></a></p>
					</div>
				</div>
				<span style="font-weight:bold;">THE CENTER</span>
			</a>
		</li>
		<li>
			<a href="/contacts" style="text-decoration:none;">
				<div class="ch-item ch-img-3">
					<div class="ch-info">
						<h3 style="margin-bottom:-80px;"><br>About us</h3>
						<p style="font-size:18px;">Paint for Future <a href="/contacts"></a></p>
					</div>
				</div>
				<span style="font-weight:bold;">ABOUT US</span>
			</a>
		</li>
	</ul>
</section>

app/views/home/_donate.html.erb
<ul style="margin-bottom:20px;">
  <% @messages.each do |message| %>
  	<% if message.message_type == "Donate Message" %>
	    <li>
	      <h1 class="main-heading" style="margin-left:0px;"><%= message.title.html_safe if message.title? %></h1>
	      <div class="donate-info">
	        <hr>
	        <p class="donate"><%= message.content.html_safe if message.content? %></p>
	      </div>
	    </li>
  	<% end %> 
  <% end %> 
</ul>  

app/views/home/_footer.html.erb
<div id="wrapper">
	<%= render :partial => "home/share_links" %>
  <div itemscope itemtype="http://schema.org/Organization">
    <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
      <footer class="main-footer">
        <p>
          Org: 802477-6331 &copy; 2012 &nbsp; <span itemprop="email">info@paintforfuture.org</span>, <span itemprop="streetAddress">  Östermalmsgatan 58, 5 Tr.  </span><span itemprop="postalCode"> 114 50 </span> <span itemprop="addresLocality"> Stockholm, Sweden </span>
        </p>
      </footer>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<div id="wrapper">
  <header>
    
    <%= link_to (image_tag ("logo-small.png"), :width => "150px", :height => "120px", :title => "Paint for Future"), home_index_path %> 
  <a href="<%= home_index_path %>">
    <div id="main-title">
      <h1 style="font-size:48px;margin-left:-50px;margin-top:10px;">PAINT FOR FUTURE</h1>
      <h3 style="margin-left:-50px;">AID THROUGH ART</h3>
     </div> 
  </a>
    <div id="menu-wrapper">
      <div class="container">
        <div class="navbar">
          <div class="navbar-inner">
            <%= link_to "Paint for Future", home_index_path, :class => "brand", :id => "bootstrap-menu-title" %>
            <ul class="nav" id="bootsrap-menu-items">
              <li class=<%= is_current_page(projects_path) %>> 
                <%= link_to "THE PROJECT", projects_path %>
              </li>
              <li class=<%= is_current_page(goals_path) %>>
                 <%= link_to "THE CENTER", goals_path %>
              </li>
              <li class=<%= is_current_page(videos_path) %>>
                <%= link_to "PARTNERS", videos_path %>
              </li>
              <li class=<%= is_current_page(galleries_path) %>>
                <%= link_to "GALLERY", galleries_path %>
              </li>
              <li class=<%= is_current_page(posts_path) %>>
                <%= link_to "NEWS", posts_path %>
              </li>
              <li class=<%= is_current_page(contacts_path) %>>
                 <%= link_to "ABOUT US", contacts_path %>
              </li>
            </ul>
          </div>
        </div>  
      </div>
    </div>
    <% unless is_current_page(galleries_path) == "active" %>
      <ul id="dropdown">
        <li><a href="#" id="follow-text">SHARE</a>
          <ul>
            <li>       
              <div class="fb-like" data-href="http://www.paintforfuture.org/" data-send="true" data-layout="button_count" data-width="150" data-show-faces="false" data-font="trebuchet ms"></div>
            </li>
            <li>
              <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.paintforfuture.org/" data-hashtags="paintforfuture">Tweet</a>
            </li>
            <li>
              <div class="g-plus" data-action="share"></div>
            </li>       
           </ul>
        </li>
      </ul>
    <% end %>
  </header>
</div>

app/views/home/_partners.html.erb
<div id="partners-footer">
	<hr>
	<ul id="partners">
		<% @partners.each do |partner| %>
			<li>
    		<%= image_tag partner.logo %>
			</li>
		<% end %> 	
		<li></li>
	</ul>
</div>

app/views/home/_paypal_donate.html.erb
<div id="partners-header-donate">	
	<!-- Paypal Donate button -->
	<p style="text-align:center;margin-bottom:2px;">Donate via Paypal</p>
	<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="hosted_button_id" value="P6KW4Y6RT5SP4">
		<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
		<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
	</form><!-- END Paypal Donate button -->
</div>		

app/views/home/_pdf_links.html.erb
<ul class="documents">
  <h1 id="documents-heading" class="main-heading">Documents</h1>
  <hr id="document-divider">
  <% @messages.reverse.each do |message| %> 
    <% if message.message_type == "PDF-links" %>
      <li class="document-link">  
        <h1>
          <%= message.title.html_safe if message.title? %> 
          <span>
            <%= message.content.html_safe if message.content? %>
          </span>
        </h1>
      </li>
    <% end %>
  <% end %> 
</ul>

app/views/home/_share_links.html.erb
<div id="home-share-buttons">
			
	<div class="fb-like" data-href="http://www.paintforfuture.org" data-send="true" data-layout="button_count" data-width="150" data-show-faces="false" data-font="trebuchet ms" style="margin-right:30px;"></div>

  <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.paintforfuture.org" data-hashtags="paintforfuture">Tweet</a> 	

  <div class="g-plus" data-action="share"></div>

</div>

app/views/home/index.html.erb
<div id="wrapper">
	<h3 id="slogan">
		Discover the new generation of artists						
	</h3>
  <div class="sideshow-container">
		<div class="slider-container">
			<div id="slideshow" class="nivoSlider">
        <%= image_tag "slides/slide3.jpg" %>
        <%= image_tag "slides/slide1.jpg" %>
			</div><!-- end of slideshow -->
		</div>
	</div><!-- end of slideshow -->
	<% unless @homepage_message == nil %>
		<div id="homepage-message">
			<h3><%= @homepage_message.title %></h3>
			<%= raw @homepage_message.content %>
		</div>
	<% end %>
	<%= render "home/circle_links" %>
	<%= render "home/paypal_donate" %>		
	<%= render "home/partners" %>
  <%= javascript_include_tag "homes" %>
</div>