config/routes.rb
Future::Application.routes.draw do
  Mercury::Engine.routes

  get "message/index"

  resources :galleries

  resources :videos, :path =>  "/partners"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :contacts do 
    member { post :show }
  end

  resources :projects

  resources :goals, :path => "/center"

  resources :posts, :path => "/news" do
    member { post :show }
  end
  

  match "/posts/:id" => 'posts#show' 
  match "/posts" => 'posts#index' 
  match "/blog" => 'posts#index'

  match "/videos" => 'videos#index'

  get "home/index"

  root :to => "home#index"

  match "/sitemap.:format",
     :controller => "home",
     :action => "sitemap",
     :conditions => { :method => :get }

 
 mount Ckeditor::Engine => "/ckeditor"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :phone_number, :description, :job_title, :image, :website, :position
  mount_uploader :image, PostImageUploader
  validates :name, :presence => true
  validates :email, :presence => true
  validates :position, :presence => true
  validates :position, :inclusion => 1..100

  def to_param
  	"#{id} #{name}".parameterize
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	attr_accessible :description, :image, :video, :url_for_video
	mount_uploader :image, PostImageUploader
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :title, :content, :maps
end

app/models/message.rb
class Message < ActiveRecord::Base
 validates :content, :message_type, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :image, :title, :name, :content, :remote_image_url, :published_at, :sub_title, :publish
  mount_uploader :image, PostImageUploader
  validates :name, :title, :published_at, :content, :presence => true

  scope :all
  scope :published_posts, where(:publish => true)
  scope :unpublished_posts, where(:publish => false)


  def to_param
  	"#{id} #{sub_title}".parameterize
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :content
  validates :title, :presence => true, :length => { :minimum => 3 }
  validates :content, :presence => true
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :title, :description, :logo, :homepage, :homepage_slogan, :position
  validates :homepage, :presence => true
  validates :homepage_slogan, :presence => true
  validates :position, :presence => true
  validates :position, :inclusion => 1..100
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order("position asc")
    @partners = Video.order("position asc")
    @messages = Message.order("created_at desc")

    @admin = current_admin_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    @admin = current_admin_user

    if params[:content] != nil && @admin != nil 
      mercury_contact = @contact
      mercury_contact.description = params[:content][:contact_description][:value] if params[:content][:contact_description] != nil
      mercury_contact.save!
      render text: ""  
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @contact }
      end
    end

  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
    @partners = Video.order("position asc")
    @messages = Message.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goals }
    end
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = Goal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @goal }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@partners = Video.order("position asc")
    messages = Message.order("created_at desc")
    @homepage_message = nil
    messages.each do |message|
    	@homepage_message = message if message.message_type == "Homepage Message"
    end
  end

  def sitemap
  	@posts = Post.all
  	@contacts = Contact.all
  	@galleries = Gallery.all
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # GET /posts
  # GET /posts.json
  def index
    #nil if not logged in as admin
    @is_admin = current_admin_user
    if @is_admin != nil
      @posts = Post.order("created_at desc").page(params[:page]).per(10)
    else
      @posts = Post.published_posts.order("created_at desc").page(params[:page]).per(10)
    end

    @messages = Message.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.rss { render :layout => false }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    @is_admin = current_admin_user

    if params[:content] != nil && @is_admin != nil
      mercury_post = @post
      mercury_post.title = params[:content][:post_title][:value]
      mercury_post.content = params[:content][:post_content][:value]
      mercury_post.sub_title = params[:content][:post_sub_title][:value] if params[:content][:post_sub_title] != nil
      
      if params[:content][:post_publish][:value] != nil
        publish = params[:content][:post_publish][:value].chomp
        if publish.downcase == "true" 
          mercury_post.publish = true
        else
          mercury_post.publish = false
        end
      end 
      mercury_post.save!
      render text: ""
      else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @post }
      end
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base
  def index
    @videos = Video.order("created_at desc").page(params[:page]).per(10)
    @messages = Message.order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


	def is_current_page(path)
	  "active" if current_page?(path)
	end

 # def markdown(text)
    #Markdown.new(text, :hard_wrap, :autolink).to_html.html_safe
  #  rndr = Redcarpet::Render::HTML.new(:autolink => true, :hard_wrap => true)
  #  Redcarpet::Markdown.new(text, rndr);
#  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/contacts/index.html.erb
<div id="wrapper">
  
  <%= render :partial => "home/announcement" %>
  
  <%= render :partial => "home/about_us" %>

  <h1 class="main-heading">Project coordinators</h1>
 
  <ul class="cards">
    <% @contacts.each do |contact| %>
      <li>
      
        <%= image_tag contact.image_url(:thumb).to_s, :size => "80x100" if contact.image? %>

        <div class="info">
          <h1><%= link_to contact.name, contact %></h1>
          <hr>
          <p><%= contact.job_title.html_safe if contact.job_title? %></p>
          <p><%= contact.email.html_safe %></p>
          <% if contact.website? %> 
            <p><%= link_to contact.website, contact.website, :class => "external-links"%></p>
          <% else %> 
            <p><%= contact.phone_number %></p> 
          <% end %>
          <% if @admin != nil %>
            <%= link_to "Edit contact", "/editor" +  contacts_path + "/" + contact.id.to_s, :class => "edit_contact" %>
          <% end %>
      </li>
    <% end %>
  </ul>  
  <br>
  <div style="margin-bottom:-10px;">
    <b>Follow us on:</b> 
    <br>
    <%= link_to image_tag("icons/facebook.png", :size => "34x34"), "http://www.facebook.com/Paintforfuture", :title => "follow on Facebook", :id => "share-buttons", :class => "external-links" %>
    <%= link_to image_tag("icons/twitter.png", :size => "34x34"), "http://twitter.com/paintforfuture", :title => "follow on Twitter", :id => "share-buttons", :class => "external-links" %>
  </div>

  <%= render "home/donate" %> 
  <%= render "home/pdf_links"  %>
  <%= render "home/paypal_donate" %>
  <%= render "home/partners" %>


</div>

app/views/contacts/show.html.erb
<div id="wrapper">
  <ul class="posts">
    <li>
      <header>
        <h1><%= link_to @contact.name, @contact %></h1>
      </header>
      <body>
        <div class="text">
          <p>
            <div id="contact_description" class="mercury-region" data-type="editable">
              <%= raw @contact.description if @contact.description? %>
            </div>  
          </p>
          <br>
          <p><i><%= @contact.job_title.html_safe if @contact.job_title? %></i>
          <p><%= mail_to @contact.email %></p>
          <p><%= @contact.phone_number %></p>
          <p><%= link_to @contact.website, @contact.website, :class => "external-links" %></p>
          
          <% if @is_admin != nil %>
            <%= link_to "Edit contact", "/editor" + request.path, id: "edit_contact_link" %>
          <% end %>
       </div>
      <%  if @contact.image? %>
        <%= link_to (image_tag @contact.image_url(:thumb).to_s), contact_path(@contact), :id => "fancybox", :href =>  @contact.image_url().to_s %>
      <% end %>
    </body>
    </li>
  </ul>
</div>

app/views/goals/index.html.erb
<div id="wrapper">

  <div class="goals">
    <% @goals.each do |goal| %>

      <h1><%= goal.title if goal.title? %></h1>
      <div class="text">
        <p><%= goal.content.html_safe if goal.content? %></p>
      </div>
    <% end %>
    <h1>Some of The Needy Today's artists</h1>
    <div id="img-container">
      <%= image_tag "orphanage/11.jpg" %>
      <%= image_tag "orphanage/12.png" %>
      <%= image_tag "orphanage/13.jpg" %>
      <%= image_tag "orphanage/goals4.png", :size => "142x213" %>
    </div>
  </div>
  <div style="margin-bottom:30px;">
    <%= render :partial => "home/paypal_donate" %>
  </div>
</div>

app/views/message/index.html.erb
<h1>Message#index</h1>
<p>Find me in app/views/message/index.html.erb</p>

app/views/posts/index.html.erb
<div id="wrapper">
  <% @posts.each do |post| %>
    <ul class="posts"> 
      <li>
        <header>
          <h1>
            <% if post.title? %>
              <%= link_to post.title.upcase, post %>
            <% end %>
            <% unless post.publish %>
              <span style="color:red;">(UNPUBLISHED)</span>
            <% end %>
          </h1>   
        </header>

        <body>
          <div class="text">
            <p>
              <% if post.sub_title? %>
                <b><%= post.sub_title.html_safe %></b>
                <br>
                <br>
              <% end %>
              <%= raw post.content %>
            </p>
            <% if admin_logged_in %>
              <h1><%= link_to "Edit post", "/editor" +  posts_path + "/" + post.id.to_s, :class => "edit_post" %></h1>
            <% end %>
          </div>

          <% if post.image? %>
             <%= link_to (image_tag post.image_url(:thumb).to_s), post, :class => "fancybox", :href => post.image_url().to_s, :rel =>"posts-images" %>
          <% end %>
        </body>

        <hr>
        <div class="meta-text">
            <% if post.name == "SUSANNE HOLMSATER" %>
              <p><%= "#{post.published_at.upcase},  #{post.created_at.year}" if post.published_at? %> by <b>SUSANNE HOLMSÄTER</b></p>
            <% else %>
              <p><%= "#{post.published_at.upcase},  #{post.created_at.year}" if post.published_at? %> by <b><%= post.name.upcase %></b></p>
            <% end %>
         </div>
      </li>
    </ul>
  <% end %>
      

  <ul class="pagination">
    <li>
    <h1><%= paginate @posts %></h1>
    </li>
  </ul>

  <b>Follow us on:</b> 
  <br>
  <%= link_to image_tag("icons/facebook.png", :size => "34x34"), "http://www.facebook.com/Paintforfuture", :title => "follow on Facebook", :id => "share-buttons", :class => "external-links" %>
  <%= link_to image_tag("icons/twitter.png", :size => "34x34"), "http://twitter.com/paintforfuture", :title => "follow on Twitter", :id => "share-buttons", :class => "external-links" %>
  <%= link_to image_tag("icons/rss.png", :size => "34x34"), "http://feeds.feedburner.com/PaintForFuture-News", :title => "Subscribe to rss", :id => "share-buttons", :class => "external-links", :type => "application/rss+xml" %>

</div> 

app/views/posts/show.html.erb
<div id="wrapper">
 <ul class="posts"> 
      <li>
        <header>
          <% if @post.title? %>
            <h1 id="post_title" style="margin-left:20px;" class="mercury-region" data-type="editable">
              <%= @post.title.upcase %>
            </h1>   
          <% end %>
        </header>

        <body>
          <div class="text">
              <p>
                <% if @post.sub_title? %>
                  <b id="post_sub_title" class="mercury-region" data-type="editable"><%= @post.sub_title.html_safe %></b>
                  <br>
                  <br>
                <% end %>
                <div id="post_content" class="mercury-region" data-type="editable">
                  <%= raw @post.content %>
                </div>

              </p>
              <% if admin_logged_in %>
                <%= link_to "Edit post", "/editor" + request.path, id: "edit_post_link" %>
                <p style="color:red;">
                  <% if @post.publish %>
                    <input id="post_publish_checkbox" type="checkbox" value="true"> Publish?
                  <% else %>
                    <input id="post_publish_checkbox" type="checkbox" value="false"> Publish?
                  <% end %>
                  <div id="post_publish" class="mercury-region" data-type="editable" style="display:none;">
                    <% if @post.publish %>
                      <p>true</p>
                    <% else %>
                      <p>false</p>
                    <% end %>
                  </div>
                </p>
              <% end %>
          </div>
          <% if @post.image? %>
             <%= link_to (image_tag @post.image_url(:thumb).to_s), @post, :class => "fancybox", :href => @post.image_url().to_s %>
          <% end %>
        </body>
        <hr>
        <div class="meta-text" style="margin-bottom:50px;">
            <% if @post.name == "SUSANNE HOLMSATER" %>
              <p><%= "#{@post.published_at.upcase},  #{@post.created_at.year}" if @post.published_at? %> by <b>SUSANNE HOLMSÄTER</b></p>
            <% else %>
              <p><%= "#{@post.published_at.upcase},  #{@post.created_at.year}" if @post.published_at? %> by <b><%= @post.name.upcase if @post.name? %> </b></p>
            <% end %>
        </div>
      </li>
    </ul>
    
</div>  
  

app/views/videos/index.html.erb
<title> Paint for Future - Partners</title><div id="wrapper">  		<ul class="videos">		<li><h1 style="border-bottom: 1px solid black;font-size:32px;width:600px;">Sponsors and Partners</h1></li>		<% @videos.each do |video| %>	  		<li><h1><%= video.title if video.title? %></h1></li>	    	<li>	    		<% if video.logo? && video.homepage? %>		    		<%= link_to video.homepage, :class => "external-links" do %>			    		<%= image_tag video.logo %> 		    		<% end %>	    		<% end %>	    		<br>	    		<%= video.description.html_safe if video.description? %>	    		<br>	    		<%= link_to video.homepage, video.homepage, :class => "external-links" %> - <%= video.homepage_slogan %>	    	</li>	    	<br>	    	<br>	    	<hr style="width:600px;">		<% end %>	</ul>  <div style="margin-bottom:30px;">    <%= render :partial => "home/paypal_donate" %>  </div></div>